name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: piper help
      uses: SAP/project-piper-action@master
      with:
        command: help
    - name: piper step  
      uses: SAP/project-piper-action@master
      with:
        command: mavenExecute

